site_name: Hololens 2
theme:
  name: material
  language: fr
  palette:
    scheme: slate
    primary: indigo
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  icon:
    admonition:
      warning: octicons/alert-16
      info: octicons/info-16
nav:
  - Accueil: index.md
  - Installations et configurations:
    - Prise en main: configuration/prise_en_main.md
    - Hololens 2 sur Unity: configuration/developper_avec_unity.md
markdown_extensions:
  - admonition
  - md_in_html
extra_css:
  - stylesheets/extra.css