site_name: Polytech Nancy - Hololens 2
theme:
  name: material
  language: fr
  palette:
    scheme: slate
    primary: black
  icon:
    logo: material/hololens
    admonition:
      warning: octicons/alert-16
      info: octicons/info-16
  features:
    - navigation.footer
    - content.footnote.tooltips
    - content.tooltips
nav:
  - 📌 Accueil: index.md
  - 📃 Préréquis:
    - Télécharger Outils/Logiciels: prerequis/outils_logiciels.md
    - Prise en main d'Unity: prerequis/unity.md
    - Configurer Visual Studio: prerequis/visual_studio.md
  - 🛠️ Configurations:
    - Prise en main: configuration/prise_en_main.md
    - Hololens 2 sur Unity: configuration/developper_avec_unity.md
    - Lancement du projet sur Hololens 2: configuration/lancement_projet.md
    - Vuforia: configuration/vuforia.md
  - 💻 Développement:
    - Objets manipulables: developpement/objets_manipulables.md
    - Interface utilisateur: developpement/interface_utilisateur.md
    - Utiliser Vuforia: developpement/utiliser_vuforia.md
    - Localisation: developpement/localisation.md
    - Build le projet: developpement/build_projet.md
markdown_extensions:
  - admonition
  - md_in_html
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css
repo_url: https://github.com/WashiFR/Hololens-Doc
repo_name: WashiFR/Hololens-Doc